#!/bin/bash
#
# xscontainer-monitor Start/Stop the xscontainer monitor service
#
# chkconfig: 2345 24 76
# description: XenServer Container Monitor
# processname: xscontainer-monitor

. /etc/init.d/functions

NAME="xscontainer-monitor"
CMD=$(which xscontainer-monitor)
LOCKFILE=/var/lock/subsys/xscontainer-monitor

start() {
    echo -n $"Starting ${NAME}: "
    APID=$(pidof -x "${CMD}")
    if [ $? -eq 0 ]; then
        failure $"$base startup"
        echo
        return 1
    fi

    nohup ${CMD} > /dev/null 2>&1 &
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        touch "$LOCKFILE"
        success $"$base startup"
    else
        failure $"$base startup"
    fi
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $NAME: "
    killproc "$CMD"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f "$LOCKFILE"

    # Delete idrsa to avoid that the host holds on to the key, although it has
    # left the pool
    rm -f /opt/xensource/packages/files/xscontainer/xscontainer-idrsa

    return $RETVAL
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

