#!/usr/bin/env python

from xcp.supplementalpack import *
from optparse import OptionParser

parser = OptionParser()
parser.add_option('--pln', dest="platform_name")
parser.add_option('--plv', dest="platform_version")
parser.add_option('--bld', dest="build")
parser.add_option('--out', dest="outdir")
parser.add_option('--spn', dest="sp_name")
parser.add_option('--spd', dest="sp_description")
parser.add_option('--ver', dest="version")
(options, args) = parser.parse_args()

xs = Requires(originator='xcp', name='main', test='ge',
              product=options.platform_name, version=options.platform_version)

setup(originator='xs', name=options.sp_name, product=options.platform_name,
      version=options.version, build=options.build, vendor='Citrix Systems, Inc.',
      description=options.sp_description, packages=args, requires=[xs],
      outdir=options.outdir, output=['iso'])
