#!/usr/bin/env python

import XenAPIPlugin
import sys
# ToDo: hack for building on Fedora
sys.path.append('/usr/local/lib/python2.7/dist-packages/')
import xscontainer.Docker as Docker
import xscontainer.CoreOs as CoreOs


def check_args(reqs, args):
    for req in reqs:
        if req not in args:
            raise Exception('INVALID_ARGUMENTS')

def prepare_output(output):
    return "True%s" %(output)

def install_vm(session, args):
    check_args(['url', 'sruuid'],  args)
    return prepare_output(CoreOs.install_vm(session,
                                            args['url'],
                                            args['sruuid']))


def create_config_drive(session, args):
    check_args(['vmuuid', 'sruuid', 'configuration'], args)
    configuration = args['configuration'].replace("%BR%", "\r\n")
    return prepare_output(CoreOs.create_config_drive_xml(session,
                                                         args['vmuuid'],
                                                         args['sruuid'],
                                                         configuration))


def get_config_drive_default(session, args):
    check_args(['templateuuid'], args)
    return prepare_output(CoreOs.CLOUDCONFIG)


def get_config_drive_configuration(session, args):
    check_args(['vdiuuid'], args)
    return  prepare_output(CoreOs.get_config_drive_configuration(session,
                                                                args['vdiuuid']
                                                               ))


def get_version(session, args):
    check_args(['vmuuid'], args)
    return prepare_output(Docker.get_version_xml(session, args['vmuuid']))


def get_info(session, args):
    check_args(['vmuuid'], args)
    return prepare_output(Docker.get_info_xml(session, args['vmuuid']))


def get_inspect(session, args):
    check_args(['vmuuid', 'object'], args)
    return prepare_output(Docker.get_inspect_xml(session, args['vmuuid'],
                                                 args['object']))


def start(session, args):
    check_args(['vmuuid', 'container'], args)
    return prepare_output(Docker.start(session, args['vmuuid'],
                                       args['container']))


def stop(session, args):
    check_args(['vmuuid', 'container'], args)
    return prepare_output(Docker.stop(session, args['vmuuid'],
                                      args['container']))


def restart(session, args):
    check_args(['vmuuid', 'container'], args)
    return prepare_output(Docker.restart(session, args['vmuuid'],
                                         args['container']))


def pause(session, args):
    check_args(['vmuuid', 'container'], args)
    return prepare_output(Docker.pause(session, args['vmuuid'],
                                       args['container']))


def unpause(session, args):
    check_args(['vmuuid', 'container'], args)
    return prepare_output(Docker.unpause(session, args['vmuuid'],
                                         args['container']))


def passthrough(session, args):
    check_args(['vmuuid', 'command'], args)
    return prepare_output(Docker.passthrough(session, args['vmuuid'],
                                             args['command']))

if __name__ == "__main__":
    """
    # Ensure that VM specific operations are run on the right slave
    for arg in sys.argv:
        if arg.startswith('args:vmuuid='):
            vmuuid=arg.replace('args:vmuuid=', '')
            vmrecord = XenApi.get_vm_record_by_uuid(vmuuid)
            hostref = vmrecord['resident-on']
            if hostref != get_this_host_ref():
                print XenAPIPlugin.call_plugin(session, hostref, 'docker', args)
                exit(0)
    """

    XenAPIPlugin.dispatch({
        'install_vm': install_vm,
        'create_config_drive': create_config_drive,
        'get_config_drive_default': get_config_drive_default,
        'get_config_drive_configuration': get_config_drive_configuration,
        'get_info': get_info,
        'get_version': get_version,
        'get_inspect': get_inspect,
        'start': start,
        'stop': stop,
        'restart': restart,
        'pause': pause,
        'unpause': unpause,
        'passthrough': passthrough, })
