#!/usr/bin/env python

import sys
# @todo: Workaround for building outside the build system
sys.path.append('/usr/local/lib/python2.7/dist-packages/')
import xscontainer.docker_monitor as docker_monitor


def main():
    docker_monitor.monitor_host()

if __name__ == "__main__":
    main()
