#!/usr/bin/env python

import sys
import sys
# ToDo: hack for building on Fedora
sys.path.append('/usr/local/lib/python2.7/dist-packages/')
import xscontainer.Util as Util
import xscontainer.DockerMonitor as DockerMonitor


def main():
    DockerMonitor.monitor_host()

if __name__ == "__main__":
    main()
