#!/usr/bin/env python

import sys
# ToDo: hack for building on Fedora
sys.path.append('/usr/local/lib/python2.7/dist-packages/')
import xscontainer.util as util
import xscontainer.docker_monitor as docker_monitor


def main():
    docker_monitor.monitor_host()

if __name__ == "__main__":
    main()
